import { createContext, useContext, useMemo, useState } from 'react';

const translations = {
  en: {
    navFeatures: 'Features',
    navHowItWorks: 'How It Works',
    navWeather: 'Weather',
    navContact: 'Contact',
    getStarted: 'Get Started',
    footerTagline: 'Pure guidance for smarter farming.',
    footerEmail: 'Email',
    footerPhone: 'Phone',
    footerRights: 'Copyright © 2026 Smart Krishi Assistant. All rights reserved.',
    languageLabel: 'Language',
    cropEyebrow: 'Crop intelligence',
    cropTitle: 'Find the right crop for your field conditions.',
    cropDescription: 'Feed your nutrient values and environmental conditions into the model, and receive a clearer recommendation in simple language.',
    cropBadge: 'Clear crop guidance',
    recommendCrop: 'Recommend Crop',
    recommending: 'Recommending...',
    recommendedOutput: 'Recommended Output',
    cropPlaceholder: 'Your crop suggestion will bloom here.',
    cropGuidance: 'The result is shown in a simple, farmer-friendly sentence.',
    diseaseEyebrow: 'Leaf disease detection',
    diseaseTitle: 'Upload a crop leaf and get a clear diagnosis.',
    diseaseDescription: 'The result appears in simple language and can be played aloud for easier understanding.',
    diseaseBadge: 'Clear disease guidance',
    chooseLeaf: 'Choose a leaf image for analysis',
    uploadHint: 'JPG, PNG, or any supported image format. Clear leaf photos work best.',
    detectDisease: 'Detect Disease',
    analyzingImage: 'Analyzing image...',
    detectionResult: 'Detection Result',
    confidence: 'Confidence',
    previewPlaceholder: 'Leaf preview will appear here',
    diseaseWaiting: 'Upload a leaf photo with good lighting and your result will appear here in simple language.',
    weatherEyebrow: 'Live weather scene',
    weatherTitle: 'A standout weather page built around your exact location.',
    weatherDescription: 'Tap once, share your coordinates through the browser, and get a natural-language weather summary with speech playback.',
    weatherBadge: 'Weather in simple language',
    locationReady: 'Use my current location',
    fetchWeather: 'Use Current Location',
    fetchingWeather: 'Fetching weather...',
    weatherReady: 'Ready for live weather',
    weatherWaiting: 'Beautiful cards, live sky vibes, and clear weather guidance.',
    listenSuggestion: 'Click here to listen to the suggestion.',
    listen: 'Pronounce',
    stop: 'Stop',
    explanation: 'Explanation',
    featureSpotlight: 'Project Enhancement',
    featureTitle: 'Clear farming guidance in every result.',
    featureDescription: 'Crop, disease, and weather outputs now feel simpler, clearer, and easier to understand in multiple languages.',
    homeHeroEyebrow: 'AI-Powered Agriculture',
    homeHeroTitleOne: 'Graceful farming intelligence',
    homeHeroTitleTwo: 'for every field decision',
    homeHeroDescription: 'Smart Krishi turns model outputs into calm, actionable guidance with multilingual support and spoken suggestions for farmers.',
    startFree: 'Start Free',
    exploreWeather: 'Explore Weather',
    freeToUse: 'Free to use',
    multilingual: 'Hindi, Telugu, English',
    voiceSupport: 'Speech guidance',
    featuresHeading: 'Everything You Need to Farm Smarter',
    featuresDescription: 'Aesthetic interfaces and practical tools designed to feel modern, warm, and easy to trust.',
    howHeading: 'Simple as 1-2-3',
    howStep1Title: 'Share your farm details',
    howStep1Text: 'Enter field values, upload a leaf image, or fetch your local weather.',
    howStep2Title: 'Get clear guidance',
    howStep2Text: 'Your result is turned into short, easy-to-understand advice.',
    howStep3Title: 'Read or listen',
    howStep3Text: 'See the answer in your language and play it aloud with one tap.',
    weatherHeading: 'Real-Time Weather Insights',
    contactHeading: 'Ready to bring AI into your farm workflow?',
    contactDescription: 'Explore crop recommendations, disease detection, live weather insights, and multilingual explanations from one polished experience.',
    openWeatherTool: 'Open Weather Tool',
    outputSummary: 'Output Summary',
    featureCropText: 'Get crop recommendations explained in simple language instead of raw output.',
    featureDiseaseText: 'Upload leaf photos and receive clear disease guidance that is easier to follow.',
    featureWeatherText: 'Turn live weather data into practical field guidance in your preferred language.',
    featureSpeechText: 'Use the pronounce button to listen to suggestions in English, Hindi, or Telugu.',
  },
  hi: {
    navFeatures: 'विशेषताएँ',
    navHowItWorks: 'कैसे काम करता है',
    navWeather: 'मौसम',
    navContact: 'संपर्क',
    getStarted: 'शुरू करें',
    footerTagline: 'बेहतर खेती के लिए सरल मार्गदर्शन।',
    footerEmail: 'ईमेल',
    footerPhone: 'फ़ोन',
    footerRights: 'कॉपीराइट © 2026 स्मार्ट कृषि असिस्टेंट। सर्वाधिकार सुरक्षित।',
    languageLabel: 'भाषा',
    cropEyebrow: 'फसल मार्गदर्शन',
    cropTitle: 'अपने खेत की स्थिति के लिए सही फसल चुनें।',
    cropDescription: 'पोषक तत्व और मौसम के मान भरें, और परिणाम को आसान भाषा में देखें।',
    cropBadge: 'सरल फसल मार्गदर्शन',
    recommendCrop: 'फसल सुझाएँ',
    recommending: 'सुझाव लिया जा रहा है...',
    recommendedOutput: 'सुझाया गया परिणाम',
    cropPlaceholder: 'आपका फसल सुझाव यहाँ दिखाई देगा।',
    cropGuidance: 'परिणाम किसान-मित्र भाषा में दिखाया जाता है।',
    diseaseEyebrow: 'पत्ती रोग पहचान',
    diseaseTitle: 'पत्ती अपलोड करें और स्पष्ट निदान पाएँ।',
    diseaseDescription: 'परिणाम सरल भाषा में दिखता है और उसे सुनना भी आसान है।',
    diseaseBadge: 'सरल रोग मार्गदर्शन',
    chooseLeaf: 'विश्लेषण के लिए पत्ती चुनें',
    uploadHint: 'JPG, PNG या समर्थित चित्र प्रारूप। साफ पत्ती की तस्वीरें बेहतर रहती हैं।',
    detectDisease: 'रोग पहचानें',
    analyzingImage: 'चित्र का विश्लेषण हो रहा है...',
    detectionResult: 'पहचान परिणाम',
    confidence: 'विश्वास स्तर',
    previewPlaceholder: 'पत्ती का पूर्वावलोकन यहाँ दिखाई देगा',
    diseaseWaiting: 'अच्छी रोशनी में पत्ती की फोटो अपलोड करें, परिणाम यहाँ सरल भाषा में दिखाई देगा।',
    weatherEyebrow: 'लाइव मौसम दृश्य',
    weatherTitle: 'आपकी सटीक लोकेशन पर आधारित शानदार मौसम पेज।',
    weatherDescription: 'एक बार टैप करें, स्थान साझा करें, और सरल भाषा में मौसम सारांश के साथ आवाज़ में सुनें।',
    weatherBadge: 'सरल मौसम मार्गदर्शन',
    locationReady: 'मेरी वर्तमान लोकेशन उपयोग करें',
    fetchWeather: 'वर्तमान लोकेशन उपयोग करें',
    fetchingWeather: 'मौसम लाया जा रहा है...',
    weatherReady: 'लाइव मौसम के लिए तैयार',
    weatherWaiting: 'सुंदर कार्ड और साफ मौसम मार्गदर्शन।',
    listenSuggestion: 'सुझाव सुनने के लिए यहाँ क्लिक करें।',
    listen: 'सुनें',
    stop: 'रोकें',
    explanation: 'व्याख्या',
    featureSpotlight: 'प्रोजेक्ट उन्नयन',
    featureTitle: 'हर परिणाम में स्पष्ट खेती मार्गदर्शन।',
    featureDescription: 'फसल, रोग और मौसम के परिणाम अब अधिक सरल, स्पष्ट और बहुभाषी हो गए हैं।',
    homeHeroEyebrow: 'एआई आधारित कृषि',
    homeHeroTitleOne: 'हर खेत के निर्णय के लिए',
    homeHeroTitleTwo: 'शांत और सुंदर बुद्धिमत्ता',
    homeHeroDescription: 'स्मार्ट कृषि अब मॉडल परिणामों को बहुभाषी और सुनने योग्य मार्गदर्शन में बदलता है।',
    startFree: 'मुफ़्त शुरू करें',
    exploreWeather: 'मौसम देखें',
    freeToUse: 'मुफ़्त उपयोग',
    multilingual: 'हिंदी, तेलुगु, अंग्रेज़ी',
    voiceSupport: 'आवाज़ मार्गदर्शन',
    featuresHeading: 'स्मार्ट खेती के लिए आपकी हर ज़रूरत',
    featuresDescription: 'आधुनिक, भरोसेमंद और सहज अनुभव देने के लिए सुंदर इंटरफेस और उपयोगी टूल्स।',
    howHeading: 'सिर्फ 1-2-3 जितना आसान',
    howStep1Title: 'खेत की जानकारी दें',
    howStep1Text: 'फील्ड वैल्यू भरें, पत्ती की फोटो अपलोड करें या स्थानीय मौसम लें।',
    howStep2Title: 'स्पष्ट सलाह पाएँ',
    howStep2Text: 'आपके परिणाम को छोटे और आसान वाक्यों में बदला जाता है।',
    howStep3Title: 'पढ़ें या सुनें',
    howStep3Text: 'उत्तर अपनी भाषा में देखें और एक टैप से उसे सुनें।',
    weatherHeading: 'रियल-टाइम मौसम जानकारी',
    contactHeading: 'क्या आप एआई को अपनी खेती में शामिल करना चाहते हैं?',
    contactDescription: 'एक ही सुंदर अनुभव में फसल सुझाव, रोग पहचान, लाइव मौसम और बहुभाषी व्याख्याएँ पाएँ।',
    openWeatherTool: 'मौसम टूल खोलें',
    outputSummary: 'आउटपुट सारांश',
    featureCropText: 'फसल सुझाव अब कच्चे आउटपुट की जगह आसान भाषा में मिलते हैं।',
    featureDiseaseText: 'पत्ती की फोटो अपलोड करें और साफ, समझने योग्य रोग मार्गदर्शन पाएँ।',
    featureWeatherText: 'लाइव मौसम डेटा को अपनी पसंदीदा भाषा में व्यावहारिक सलाह में बदलें।',
    featureSpeechText: 'प्रोनाउन्स बटन से सुझाव हिंदी, तेलुगु या अंग्रेज़ी में सुनें।',
  },
  te: {
    navFeatures: 'లక్షణాలు',
    navHowItWorks: 'ఎలా పని చేస్తుంది',
    navWeather: 'వాతావరణం',
    navContact: 'సంప్రదించండి',
    getStarted: 'ప్రారంభించండి',
    footerTagline: 'మంచి వ్యవసాయ నిర్ణయాలకు సరళమైన మార్గదర్శనం.',
    footerEmail: 'ఇమెయిల్',
    footerPhone: 'ఫోన్',
    footerRights: 'కాపీరైట్ © 2026 స్మార్ట్ కృషి అసిస్టెంట్. అన్ని హక్కులు కలవు.',
    languageLabel: 'భాష',
    cropEyebrow: 'పంట మార్గదర్శనం',
    cropTitle: 'మీ పొలం పరిస్థితులకు సరైన పంటను తెలుసుకోండి.',
    cropDescription: 'పోషకాలు మరియు వాతావరణ విలువలను ఇవ్వండి, ఫలితాన్ని సులభమైన భాషలో చూడండి.',
    cropBadge: 'సులభమైన పంట మార్గదర్శనం',
    recommendCrop: 'పంట సూచించండి',
    recommending: 'సూచన సిద్ధమవుతోంది...',
    recommendedOutput: 'సిఫారసు ఫలితం',
    cropPlaceholder: 'మీ పంట సూచన ఇక్కడ కనిపిస్తుంది.',
    cropGuidance: 'ఫలితం రైతులకు అర్థమయ్యే సులభమైన భాషలో చూపబడుతుంది.',
    diseaseEyebrow: 'ఆకు వ్యాధి గుర్తింపు',
    diseaseTitle: 'ఆకు ఫోటో అప్‌లోడ్ చేసి స్పష్టమైన నిర్ధారణ పొందండి.',
    diseaseDescription: 'ఫలితం సులభమైన భాషలో కనిపిస్తుంది మరియు వినడానికి కూడా సౌకర్యంగా ఉంటుంది.',
    diseaseBadge: 'సులభమైన వ్యాధి మార్గదర్శనం',
    chooseLeaf: 'విశ్లేషణ కోసం ఆకు చిత్రం ఎంచుకోండి',
    uploadHint: 'JPG, PNG లేదా మద్దతు ఉన్న చిత్రం ఫార్మాట్. స్పష్టమైన ఆకు ఫోటోలు ఉత్తమం.',
    detectDisease: 'వ్యాధి గుర్తించండి',
    analyzingImage: 'చిత్రం విశ్లేషిస్తోంది...',
    detectionResult: 'గుర్తింపు ఫలితం',
    confidence: 'నమ్మక స్థాయి',
    previewPlaceholder: 'ఆకు ప్రివ్యూ ఇక్కడ కనిపిస్తుంది',
    diseaseWaiting: 'మంచి కాంతిలో తీసిన ఆకు ఫోటోను అప్‌లోడ్ చేయండి, ఫలితం ఇక్కడ సులభమైన భాషలో కనిపిస్తుంది.',
    weatherEyebrow: 'ప్రత్యక్ష వాతావరణ దృశ్యం',
    weatherTitle: 'మీ ఖచ్చితమైన ప్రదేశానికి సరిపోయే అందమైన వాతావరణ పేజీ.',
    weatherDescription: 'ఒకసారి ట్యాప్ చేసి ప్రదేశం పంచుకోండి, తరువాత సులభమైన భాషలో వాతావరణ సారాంశాన్ని శబ్దంతో వినండి.',
    weatherBadge: 'సులభమైన వాతావరణ మార్గదర్శనం',
    locationReady: 'నా ప్రస్తుత స్థలాన్ని ఉపయోగించండి',
    fetchWeather: 'ప్రస్తుత స్థలాన్ని ఉపయోగించండి',
    fetchingWeather: 'వాతావరణం తెస్తోంది...',
    weatherReady: 'ప్రత్యక్ష వాతావరణానికి సిద్ధంగా ఉంది',
    weatherWaiting: 'అందమైన కార్డులు మరియు స్పష్టమైన వాతావరణ మార్గదర్శనం.',
    listenSuggestion: 'సూచనను వినడానికి ఇక్కడ క్లిక్ చేయండి.',
    listen: 'వినండి',
    stop: 'ఆపండి',
    explanation: 'వివరణ',
    featureSpotlight: 'ప్రాజెక్ట్ మెరుగుదల',
    featureTitle: 'ప్రతి ఫలితంలో స్పష్టమైన వ్యవసాయ మార్గదర్శనం.',
    featureDescription: 'పంట, వ్యాధి, వాతావరణ ఫలితాలు ఇప్పుడు మరింత సులభంగా, స్పష్టంగా, బహుభాషగా మారాయి.',
    homeHeroEyebrow: 'ఎఐ ఆధారిత వ్యవసాయం',
    homeHeroTitleOne: 'ప్రతి పొలం నిర్ణయానికి',
    homeHeroTitleTwo: 'శాంతియుతమైన తెలివైన మార్గదర్శకం',
    homeHeroDescription: 'స్మార్ట్ కృషి ఇప్పుడు మోడల్ ఫలితాలను బహుభాషా మరియు వినిపించే మార్గదర్శకంగా మారుస్తుంది.',
    startFree: 'ఉచితంగా ప్రారంభించండి',
    exploreWeather: 'వాతావరణం చూడండి',
    freeToUse: 'ఉచిత వినియోగం',
    multilingual: 'తెలుగు, హిందీ, ఇంగ్లీష్',
    voiceSupport: 'శబ్ద మార్గదర్శనం',
    featuresHeading: 'తెలివైన వ్యవసాయం కోసం మీకు కావాల్సిన ప్రతిదీ',
    featuresDescription: 'ఆధునికంగా, నమ్మదగినలా, సులభంగా అనిపించే అందమైన ఇంటర్‌ఫేస్‌లు మరియు ఉపయోగకరమైన సాధనాలు.',
    howHeading: '1-2-3 లా సులభం',
    howStep1Title: 'పొలం వివరాలు ఇవ్వండి',
    howStep1Text: 'ఫీల్డ్ విలువలు ఇవ్వండి, ఆకు ఫోటో అప్‌లోడ్ చేయండి లేదా స్థానిక వాతావరణం తీసుకోండి.',
    howStep2Title: 'స్పష్టమైన సలహా పొందండి',
    howStep2Text: 'మీ ఫలితాన్ని చిన్న, సులభమైన వాక్యాలుగా మార్చి చూపిస్తాం.',
    howStep3Title: 'చదవండి లేదా వినండి',
    howStep3Text: 'మీ భాషలో జవాబు చూసి, ఒక ట్యాప్‌తో వినండి.',
    weatherHeading: 'రియల్-టైమ్ వాతావరణ సమాచారం',
    contactHeading: 'మీ వ్యవసాయంలో ఎఐని తీసుకురావడానికి సిద్ధమా?',
    contactDescription: 'ఒకే అందమైన అనుభవంలో పంట సూచనలు, వ్యాధి గుర్తింపు, ప్రత్యక్ష వాతావరణం, మరియు బహుభాషా వివరణలు పొందండి.',
    openWeatherTool: 'వాతావరణ సాధనం తెరవండి',
    outputSummary: 'అవుట్‌పుట్ సారాంశం',
    featureCropText: 'పంట సూచనలు ఇప్పుడు కచ్చితమైన కానీ సులభమైన భాషలో లభిస్తాయి.',
    featureDiseaseText: 'ఆకు ఫోటో అప్‌లోడ్ చేసి స్పష్టమైన, అర్థమయ్యే వ్యాధి మార్గదర్శనం పొందండి.',
    featureWeatherText: 'ప్రత్యక్ష వాతావరణ డేటాను మీ భాషలో ఉపయోగకరమైన సలహాగా మార్చుకోండి.',
    featureSpeechText: 'ప్రొనౌన్స్ బటన్‌తో సూచనలను తెలుగు, హిందీ లేదా ఇంగ్లీష్‌లో వినండి.',
  },
};

const languageMeta = [
  { code: 'en', label: 'English' },
  { code: 'hi', label: 'हिंदी' },
  { code: 'te', label: 'తెలుగు' },
];

const LanguageContext = createContext(null);

export function LanguageProvider({ children }) {
  const [language, setLanguage] = useState('en');

  const value = useMemo(
    () => ({
      language,
      setLanguage,
      languages: languageMeta,
      t: (key) => translations[language]?.[key] || translations.en[key] || key,
    }),
    [language],
  );

  return <LanguageContext.Provider value={value}>{children}</LanguageContext.Provider>;
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within LanguageProvider');
  }
  return context;
}
